source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'ThirstQuencher' do
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Charts'
pod 'ChartsRealm'
end
